gcc -o build/HalSMExecutable.o -fPIC -nostdlib -ffreestanding -c src/HalSMExecutable.c -Iinclude -Llib -lHalStringFormat -lHalFileSystem -lHalSM
ar rcs -o lib/libHalSMExecutable.a build/HalSMExecutable.o
windres src/VERSIONINFO.rc -O coff build/VERSIONINFO.res
gcc -o build/HalSMCompiler.exe src/HalSMCompilerWindows.c build/VERSIONINFO.res -Iinclude -Llib -lHalStringFormat -lHalFileSystem -lHalSM -lHalSMExecutable
:: -s ASYNCIFY_IMPORTS=["async_input_text","load","loadWasm","run"]
:: -s ASYNCIFY_IGNORE_INDIRECT
:: -sALLOW_MEMORY_GROWTH=1
::emcc -s WASM=1 src\HalSMExecutableWASM.c -Iinclude D:\hal-projects-2023\HalSM\source\HalSM.c D:\hal-projects-2023\HalStringFormat\source\HalStringFormat.c D:\hal-projects-2023\HFS\source\HalFileSystem.c src\HalSMExecutable.c -o build\HalSMExecutable.js -sWASM=1 -sTOTAL_MEMORY=100MB -s TOTAL_STACK=10mb -sEXPORTED_RUNTIME_METHODS=[ccall,cwrap,FS,addFunction,getValue] -s ASYNCIFY_STACK_SIZE=1048576 -O2 -s SINGLE_FILE -s MAIN_MODULE=1 -s ASYNCIFY=1 -sASYNCIFY_IMPORTS=["run","load","init","loadWASM","WASM_drawPixelArray"] --pre-js src/HalSMExecutable.js
:: emcc -gsource-map -s STACK_OVERFLOW_CHECK=1 -s WASM=1 src\HalSMExecutableWASM.c -Iinclude D:\hal-projects-2023\HalSM\source\HalSM.c D:\hal-projects-2023\HalSM\source\HalSMDouble.c D:\hal-projects-2023\HalSM\source\HalSMInteger.c D:\hal-projects-2023\HalSM\source\HalSMMemory.c D:\hal-projects-2023\HalStringFormat\src\HalStringFormat.c D:\hal-projects-2023\HFS\HFS\source\HalFileSystem.c src\HalSMExecutable.c -o build\HalSMExecutable.js -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4GB -s SINGLE_FILE=1 -s EXPORTED_RUNTIME_METHODS=["ccall","cwrap","addFunction","FS","getValue"] -s ASYNCIFY -s ASYNCIFY_IMPORTS=["async_input_text","run","load","init","loadWASM","WASM_drawPixelArray"] -s ALLOW_TABLE_GROWTH=1 -O2


emcc -s STACK_OVERFLOW_CHECK=2 -s WASM=1 src\HalSMExecutableWASM.c -Iinclude D:\hal-projects-2023\HalSM\source\HalSM.c D:\hal-projects-2023\HalSM\source\HalSMDouble.c D:\hal-projects-2023\HalSM\source\HalSMInteger.c D:\hal-projects-2023\HalSM\source\HalSMMemory.c D:\hal-projects-2023\HalStringFormat\src\HalStringFormat.c D:\hal-projects-2023\HFS\HFS\source\HalFileSystem.c src\HalSMExecutable.c -o build\HalSMExecutable.js -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4GB -s EXPORTED_RUNTIME_METHODS=["ccall","cwrap","addFunction","FS","getValue"] -s ASYNCIFY -s ASYNCIFY_IMPORTS=["async_input_text","run","load","init","loadWASM","WASM_drawPixelArray"] -s ALLOW_TABLE_GROWTH=1 -O3
::emcc -s STACK_OVERFLOW_CHECK=2 -s WASM=1 src\HalSMExecutableWASM.c -Iinclude D:\hal-projects-2023\HalSM\source\HalSM.c D:\hal-projects-2023\HalSM\source\HalSMDouble.c D:\hal-projects-2023\HalSM\source\HalSMInteger.c D:\hal-projects-2023\HalSM\source\HalSMMemory.c D:\hal-projects-2023\HalStringFormat\src\HalStringFormat.c D:\hal-projects-2023\HFS\HFS\source\HalFileSystem.c src\HalSMExecutable.c -o build\HalSMExecutable.js -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4GB -s EXPORTED_RUNTIME_METHODS=["ccall","cwrap","addFunction","FS","getValue"] -s ASYNCIFY -s ASYNCIFY_IMPORTS=["async_input_text","run","load","init","loadWASM","WASM_drawPixelArray"] -s ALLOW_TABLE_GROWTH=1 -O1 -g4
:: -Wl,-export=load -Wl,-export=run -Wl,-export=load_file_event_success -Wl,-export=load_file_event_error -Wl,-export=malloc -Wl,-export=free -Wl,-export=realloc -Wl,-export=calloc -Wl,-export=init
::emcc -Wl,--export-all -O0 -o build/HalSMExecutable.js -s MAIN_MODULE=1 -s SINGLE_FILE=1 -s EXPORT_ALL=1 -s INITIAL_MEMORY=1024mb -s TOTAL_MEMORY=1024mb -s TOTAL_STACK=512mb -s LINKABLE=1 -s EXPORT_ALL=1 -s EXPORTED_RUNTIME_METHODS=["ccall","cwrap","addFunction","addOnPostRun","addOnPreRun"] -s ASYNCIFY=1 -sASYNCIFY_IMPORTS=["loadWASM","SDL_CreateTextureFromSurface","hsme_d","load","init"] -Iinclude -ID:/hal-projects-2023/HalWASM/include src/HalSMExecutableWASM.c D:\hal-projects-2023\HalSM\source\HalSM.c D:\hal-projects-2023\HalStringFormat\source\HalStringFormat.c D:\hal-projects-2023\HFS\source\HalFileSystem.c src\HalSMExecutable.c
:: -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4GB -s SINGLE_FILE=1 -s MAIN_MODULE=1 -s EXPORTED_RUNTIME_METHODS=["ccall","cwrap","addFunction","addOnPostRun","addOnPreRun"] -s ASYNCIFY=1 -sASYNCIFY_IMPORTS=["loadWASM","SDL_CreateTextureFromSurface","hsme_d","load","init"] -s ALLOW_TABLE_GROWTH=1 -s STACK_SIZE=16000000 -s ASYNCIFY_STACK_SIZE=167726 -s ASSERTIONS=2 -O2 -sUSE_SDL=2
:: -s SAFE_HEAP=1